[package]
name = "sorting"
version = "0.1.0"
authors = ["waalge <waalgy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "^1.4.2"
num = "^0.3.1"
clap = "2.3.3"
rand = "0.6.x"
